services:
  node-server:
    build:
      context: ./server
      dockerfile: Dockerfile.node
    ports:
      - "3000:3000"
    volumes:
      - ./server:/server
      - /server/node_modules
    depends_on:
      - mongo
    networks:
      - app-network
  
  react-app:
    build:
      context: ./client
      dockerfile: Dockerfile.react
    ports:
      - "5173:5000"
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - node-server
  

  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

volumes:
  mongo_data:

networks:
  app-network:
    driver: bridge